package com.izivia.ocpp.core20.model.common.enumeration

enum class Actions(val value: String) {
    AUTHORIZE("authorize"),
    BOOTNOTIFICATION("bootNotification"),
    CANCELRESERVATION("cancelReservation"),
    CERTIFICATESIGNED("certificateSigned"),
    CHANGEAVAILABILITY("changeAvailability"),
    CLEARCACHE("clearCache"),
    CLEARCHARGINGPROFILE("clearCHargingProfile"),
    CLEARDISPLAYMESSAGE("clearDisplayMessage"),
    CLEAREDCHARGINGLIMIT("clearedChargingLimit"),
    CLEARVARIABLEMONITORING("clearVariableMonitoring"),
    COSTUPDATE("costUpdate"),
    CUSTOMERINFORMATION("customerInformation"),
    DATATRANSFER("dataTransfer"),
    DELETECERTIFICATE("deleteCertificate"),
    DIAGNOSTICSSTATUSNOTIFICATION("diagnosticsStatusNotification"),
    FIRMWARESTATUSNOTIFICATION("firmwareStatusNotification"),
    GET15118EVCERTIFICATE("get15118EVCertificate"),
    GETBASEREPORT("getBaseReport"),
    GETCERTIFICATESTATUS("getCertificateStatus"),
    GETCHARGINGPROFILES("getChargingProfiles"),
    GETCOMPOSITESCHEDULE("getCompositeSchedule"),
    GETDISPLAYMESSAGES("getDisplayMessages"),
    GETINSTALLEDCERTIFICATEIDS("getInstalledCertificateIds"),
    GETDIAGNOSTICS("getDiagnostics"),
    GETLOCALLISTVERSION("getLocalListVersion"),
    GETLOG("getLog"),
    GETMONITORINGREPORT("getMonitoringReport"),
    GETREPORT("getReport"),
    GETTRANSACTIONSTATUS("getTransactionStatus"),
    GETVARIABLES("getVariables"),
    HEARTBEAT("heartbeat"),
    INSTALLCERTIFICATE("installCertificate"),
    LOGSTATUSNOTIFICATION("logStatusNotification"),
    METERVALUES("meterValues"),
    NOTIFYCHARGINGLIMIT("notifyChargingLimit"),
    NOTIFYCUSTOMERINFORMATION("notifyCustomerInformation"),
    NOTIFYDISPLAYMESSAGES("notifyDisplayMessages"),
    NOTIFYEVCHARGINGNEEDS("notifyEVChargingNeeds"),
    NOTIFYEVCHARGINGSCHEDULE("notifyEVChargingSchedule"),
    NOTIFYEVENT("notifyEvent"),
    NOTIFYMONITORINGREPORT("notifyMonitoringReport"),
    NOTIFYREPORT("notifyReport"),
    PUBLISHFIRMWARE("publishFirmware"),
    PUBLISHFIRMWARESTATUSNOTIFICATION("publishFirmwareStatusNotification"),
    REPORTCHARGINGPROFILES("reportChargingProfiles"),
    REQUESTSTARTTRANSACTION("requestStartTransaction"),
    REQUESTSTOPTRANSACTION("requestStopTransaction"),
    RESERVATIONSTATUSUPDATE("reservationStatusUpdate"),
    RESERVENOW("reserveNow"),
    RESET("reset"),
    SECURITYEVENTNOTIFICATION("securityEventNotification"),
    SENDLOCALLIST("sendLocalList"),
    SETCHARGINGPROFILE("setChargingProfile"),
    SETDISPLAYMESSAGE("setDisplayMessage"),
    SETMONITORINGBASE("setMonitoringBase"),
    SETMONITORINGLEVEL("setMonitoringLevel"),
    SETNETWORKPROFILE("setNetworkProfile"),
    SETVARIABLEMONITORING("setVariableMonitoring"),
    SETVARIABLES("setVariables"),
    SIGNCERTIFICATE("signCertificate"),
    STATUSNOTIFICATION("statusNotification"),
    TRANSACTIONEVENT("transactionEvent"),
    TRIGGERMESSAGE("triggerMessage"),
    UNLOCKCONNECTOR("unlockConnector"),
    UNPUBLISHFIRMWARE("unpublishFirmware"),
    UPDATEFIRMWARE("updateFirmware");

    fun lowercase() = value.lowercase()

    fun camelCaseRequest() = "${value.replaceFirstChar { it.uppercase() }}Req"
}
